name: sccache + chef (registry)

on: push

env:
  IDENTIFIER: ${{ github.workflow }}
  DOCKER_BUILDKIT: 1
  DOCKER_BUILD_ARGS: |
    SCCACHE_BUCKET=docker-rust-sccache-test
    SCCACHE_ENDPOINT=ewr1.vultrobjects.com:443
    AWS_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_KEY }}
    SCCACHE_S3_KEY_PREFIX=${{ github.workflow }}
  CARGO_TERM_COLOR: always
  IMAGE: ghcr.io/fourbytes/gha-cargo-cache-tests

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      builder-image: ${{ steps.meta.outputs.tags }}

    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch,suffix=-${{ env.IDENTIFIER }}-builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
          buildkitd-flags: --debug
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.chef.sccache
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: builder
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cacher
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cacher,mode=max
          build-args: ${{ env.DOCKER_BUILD_ARGS }}

  test:
    needs: build
    runs-on: ubuntu-latest

    container:
      image: ${{ needs.build.outputs.builder-image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        working-directory: /app

    steps:
      - run: echo $DOCKER_BUILD_ARGS >> $GITHUB_ENV
      - name: Run tests
        run: cargo test --release

  package:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
          buildkitd-flags: --debug
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.chef.sccache
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ needs.build.outputs.builder-image }}-cacher
          build-args: ${{ env.DOCKER_BUILD_ARGS }}
